# Generated by Django 4.0.6 on 2022-10-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='assignedDoctorId',
            field=models.DateField(null=True),
        ),
    ]
