# Generated by Django 4.0.6 on 2022-10-25 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_doctormodel_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmodel',
            name='assignedDoctorId',
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='doctor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hospital.doctormodel'),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
