# Generated by Django 4.0.6 on 2022-10-25 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_remove_patientmodel_assigneddoctorid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmodel',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='patientmodel',
            name='email',
        ),
    ]
