# Generated by Django 4.0.6 on 2022-10-25 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_remove_patientmodel_doctor_remove_patientmodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='assignedDoctorId',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.doctormodel'),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='email',
            field=models.EmailField(default='', max_length=254, null=True, unique=True),
        ),
    ]
