# Generated by Django 4.0.6 on 2022-10-25 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_patientmodel_assigneddoctorid_patientmodel_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmodel',
            name='assignedDoctorId',
        ),
    ]
