# Generated by Django 4.0.6 on 2022-10-25 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_remove_patientmodel_assigneddoctorid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientmodel',
            old_name='status',
            new_name='is_accepted',
        ),
    ]
