# Generated by Django 4.0.6 on 2022-10-25 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_rename_status_patientmodel_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='doctor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hospital.doctormodel'),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
