# Generated by Django 4.0.6 on 2022-10-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_alter_patientmodel_doctor_alter_patientmodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
    ]
