# Generated by Django 4.0.6 on 2022-10-25 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_patientmodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='doctor',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.doctormodel'),
        ),
    ]
