# Generated by Django 4.0.6 on 2022-10-25 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_alter_patientmodel_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientmodel',
            old_name='Patient_name',
            new_name='patient_name',
        ),
    ]
