# Generated by Django 4.0.6 on 2022-11-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_rename_patient_name_patientmodel_patient_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255, null=True)),
                ('doctor_name', models.CharField(max_length=255, null=True)),
                ('patinet_pass', models.CharField(max_length=255, null=True)),
                ('doctor_pass', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('date', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
