# Generated by Django 4.0.6 on 2022-11-19 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_alter_appointment_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='appointment',
            new_name='AppointmentModel',
        ),
    ]
