# Generated by Django 4.0.6 on 2022-12-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0017_rename_patinet_pass_appointmentmodel_patient_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='is_discharged',
            field=models.BooleanField(default=False),
        ),
    ]
