# Generated by Django 4.0.6 on 2022-12-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_patientmodel_is_discharged'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargePatientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_pass', models.CharField(max_length=255)),
                ('assigned_doctor_name', models.CharField(max_length=255)),
                ('todaydate', models.DateField(auto_now_add=True)),
                ('mobile', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('symptoms', models.CharField(max_length=255)),
                ('roomCharge', models.IntegerField()),
                ('medicineCost', models.IntegerField()),
                ('doctorFee', models.IntegerField()),
                ('OtherCharge', models.IntegerField()),
                ('total_price', models.IntegerField()),
            ],
        ),
    ]
