# Generated by Django 4.0.6 on 2022-12-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_dischargepatientmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dischargepatientmodel',
            name='OtherCharge',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dischargepatientmodel',
            name='doctorFee',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dischargepatientmodel',
            name='medicineCost',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dischargepatientmodel',
            name='roomCharge',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dischargepatientmodel',
            name='todaydate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dischargepatientmodel',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
    ]
