# Generated by Django 4.0.6 on 2022-12-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_alter_dischargepatientmodel_othercharge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dischargepatientmodel',
            name='Patient_id',
            field=models.IntegerField(null=True),
        ),
    ]
