# Generated by Django 4.0.6 on 2022-12-23 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_dischargepatientmodel_patient_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dischargepatientmodel',
            old_name='Patient_id',
            new_name='Patient_code',
        ),
    ]
