# Generated by Django 4.0.6 on 2022-12-23 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_rename_patient_id_dischargepatientmodel_patient_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dischargepatientmodel',
            old_name='Patient_code',
            new_name='patient_code',
        ),
    ]
