# Generated by Django 4.0.6 on 2022-12-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_rename_patient_code_dischargepatientmodel_patient_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='dischargepatientmodel',
            name='assigned_doctor_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
