# Generated by Django 4.0.6 on 2022-12-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_dischargepatientmodel_assigned_doctor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
