# Generated by Django 4.0.6 on 2022-12-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0025_alter_patientmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctormodel',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/Doctor_Profile'),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/Patinet_Profile'),
        ),
    ]
