# Generated by Django 4.0.6 on 2022-12-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0027_alter_doctormodel_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='upload/Patinet_Profile'),
        ),
    ]
