# Generated by Django 4.0.6 on 2022-12-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0028_alter_patientmodel_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='profile_pic',
            field=models.ImageField(blank=True, default='upload/upload/images.jfif', null=True, upload_to='upload/Patinet_Profile'),
        ),
    ]
