# Generated by Django 4.0.6 on 2022-12-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0031_alter_patientmodel_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='upload/Patinet_Profile'),
        ),
    ]
